// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nektsfggxlhwawdteheo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5la3RzZmdneGxod2F3ZHRlaGVvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg4OTk4OTEsImV4cCI6MjA3NDQ3NTg5MX0.T0x5QrtiY38qGcX5hGlGs_ameKP6z2vK2zCNW2ufRXY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});